spring.application.name=maps
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/galacticMaps
spring.datasource.username=root
spring.datasource.password=1793
sping.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


