SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GalacticMaps` DEFAULT CHARACTER SET utf8 ;
USE `GalacticMaps` ;

CREATE TABLE IF NOT EXISTS `GalacticMaps`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `PasswordHash` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `GalacticMaps`.`Route` (
  `RouteID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `RouteName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RouteID`),
  INDEX `UserID_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `GalacticMaps`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `GalacticMaps`.`Route_Waypoints` (
  `RouteID` INT NOT NULL,
  `Seq` INT NOT NULL,
  `PlaceID` LONGTEXT NOT NULL,
  PRIMARY KEY (`RouteID`, `Seq`),
  CONSTRAINT `RouteID`
    FOREIGN KEY (`RouteID`)
    REFERENCES `GalacticMaps`.`Route` (`RouteID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
